# Create a docker compose file that will spin up a neo4j image/container

volumes:
    neo4j-data:
    neo4j-backups:

services:
    udtneo4j:
        container_name: udtneo4j
        ports:
            - "7474:7474"
            - "7687:7687"
        env_file:
            - ./env_files/.db_env
        environment:
            - NEO4J_apoc_export_file_enabled=true
            - NEO4J_apoc_import_file_enabled=true
            - NEO4J_apoc_import_file_use__neo4j__config=true
            - NEO4J_PLUGINS=\[\"apoc\"\]
        image: neo4j:5.20.0-community-bullseye
        volumes:
            - neo4j-data:/data
            - neo4j-backups:/backups
        restart: always
