FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN set -eux; \
    apt-get update; \
    apt-get -y --no-install-recommends install \
        vim \
        python3.11 \
        python3-dev \
        python3-pip \
        build-essential \
        binutils \
        libproj-dev \
        gdal-bin \
        libgdal-dev \
        cmake


#    gunicorn

RUN mkdir -p /opt/udt/cwa/cwa_geodjango/

RUN mkdir -p /opt/udt/cwm/

RUN mkdir -p /opt/udt/data/

RUN mkdir -p /opt/udt/api/api_drf/

WORKDIR /opt/udt/cwa/cwa_geodjango/


RUN pip install --upgrade pip

# EXPOSE 8000

#CMD ["gunicorn", "config.wsgi", "-b 0.0.0.0:8000", "--workers=6"]

ENTRYPOINT ["tail"]

CMD ["-f","/dev/null"]
