name: Repo Quality Checks

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, ready_for_review, edited]

  push:
    branches: [main]

jobs:
  pr-validation:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for PR description
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.pull_request.body || '';
            if (body.trim().length === 0) {
              core.setFailed("Pull Request must include a description.");
            }

      - name: Check README.md exists and is not empty
        run: |
          if [ ! -s README.md ]; then
            echo "README.md is missing or empty"
            exit 1
          else
            echo "README.md exists and is not empty"
          fi
